### ISSUE TITLE
Define development guide

### ISSUE THREAD

**Issue by junoyoon** [naver/scavenger#52]
* We didn't define development style yet surprisingly but used precisely defined editorconfig only.
* Following guides are necessary.
  * Coding style 
  * Branch / Merging policy
  * Release policy

Now.. it's the time.

**Comment by taeyeon-Kim** [comment]
I just tried to release 1.0.4 and...  I saw that I hadn't changed the version below... I thought I'd make a decision at this point.
https://github.com/naver/scavenger/blob/develop/build.gradle.kts#L7
```kotlin
allprojects {
    group = "com.navercorp.scavenger"
    version = "1.0.3"
```

**Comment by junoyoon** [comment]
Yes.. it's time to use gradle release plugin like (https://github.com/researchgate/gradle-release)

**Comment by junoyoon** [comment]
what about investigating gradle release plugin? @sohyun-ku

**Comment by sohyun-ku** [comment]
ok. I'm on vacation this week, so I'll check next week.

**Comment by junoyoon** [comment]
OK. Take your time and see u next week. :-)

**Comment by sohyun-ku** [comment]
I think current release step like below

1. make a `release` branch to modify version
2. `release` → `main` PR
3. make a TAG & Release new version at `main` 

If we use `gradle-release plugin`, I think some features make problem.
> • Creates a release tag with the current version.
> • Commits the project with the new version.

First, if we run `gradle release` at release branch, tag is created at release branch.
Second, committed version is `v1.0.1(new version)` but created tag version is `v 1.0.0(current version)`

I think’t the above problems don’t follow `3. make a TAG & Release new version at main`

Why don’t we use Github Actions instead of gradle-release-plugin?
Using a github action like below we can fire an event(ex. release, tag) when the `main` branch is pushed.

- https://github.com/actions/create-release
- https://github.com/actions/upload-release-asset

If I've missed anything, please tell me.

**Comment by sohyun-ku** [comment]
@junoyoon @taeyeon-Kim @kojandy 
https://github.com/naver/scavenger/issues/52#issuecomment-1477392705 What about this?

**Comment by kojandy** [comment]
I also think github actions might be a better solution as it can generate and upload all the release assets without manual intervention.

**Comment by junoyoon** [comment]
I think we can create release branch from master to activate the github action to release.
and no merge back this branch to master. just drop it.

what about this scheme?

**Comment by sohyun-ku** [comment]
Sounds good :)
Then I'll add github actions when pushed release branch.

**Comment by sohyun-ku** [comment]
Release policy created in #55.

```
1. develop -> main PR
  - If we want to release, PR title should be start 'release' and include ${version}
  - ex) PR title - Release v1.0.5
2. If PR is merged, trigger tag github action
  - Remove SNAPSHOT and commit to next version by gradle-release plugin
  - Create Tag in this action
3. If a tag is created, trigger create a release github action
  - Create Release in this action
```
