### ISSUE TITLE
Increase maximum methods count

### ISSUE THREAD

**Issue by hyukjin-lee** [naver/scavenger#82]
Hello, thank you for developing such a great tool.

It seems like there's a limit of 100,000 methods. I'm wondering if there are any plans to increase this limit. In my case, I'm trying to analyze a project with approximately 6 million methods, but I'm encountering issues where the scavenger is disabled due to the maximum methods count.

**Comment by kojandy** [comment]
Hello, thank you for your interest in Scavenger.

We understand the need for increasing the method count limit as per your suggestion. We will implement it shortly by exposing the limit as an option in the configuration file.
However, we recommend utilizing Scavenger's filters to precisely target the methods you want to track, since tracking a large number of methods can impact the performance of your application.

**Comment by hyukjin-lee** [comment]
Using Scavenger would be very beneficial even in the long-term testing phase, so it would be great if this feature could be added, despite a potential decrease in performance. I'll be waiting for it. Thank you.

**Comment by kojandy** [comment]
We would like to inform you that [a version including the requested feature](https://github.com/naver/scavenger/releases/tag/v1.1.1) has been released.
Starting from agent version 1.1.1, you can freely set the maximum limit by using teh `maxMethodsCount` option in `scavenger.conf`.
